language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - rustup component add clippy && cargo clippy --all --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
