[package]
name = "hdwallet"
version = "0.0.1"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/jjyr/hdwallet"
description = "Hierarchical deterministic wallet (BIP-32)"

[dependencies]
secp256k1 = "0.12"
rand = "0.6.1"
ring = "0.14.0-alpha2"
numext-fixed-uint = "0.1.2"

[dev-dependencies]
hex = "0.3.2"

